<a href="https://colab.research.google.com/github/YamilaVSosa-LP/INGENIAS-Data-Science-/blob/main/Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

arreglo_de_ceros = np.zeros(12)
print(arreglo_de_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
import numpy as np

arreglo = np.zeros(10)
arreglo[5] = 10
print(arreglo)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [3]:
import numpy as np

arreglo = np.arange(10, 50)
print(arreglo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
import numpy as np

arreglo_unidimensional = np.arange(9)
arreglo_2d = arreglo_unidimensional.reshape(3, 3)
print(arreglo_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
import numpy as np

arreglo_aleatorio = np.random.rand(100)

media = np.mean(arreglo_aleatorio)
varianza = np.var(arreglo_aleatorio)

print("Media:", media)
print("Varianza:", varianza)

Media: 0.5115314697575765
Varianza: 0.08461664512289065


In [6]:
import numpy as np

arreglo = np.array([1, 2, 3, 4, 5])

media = np.sum(arreglo) / len(arreglo)

print("Media:", media)

Media: 3.0


In [7]:
import numpy as np

arreglo = np.array([1, 2, 3, 4, 5])

media = np.mean(arreglo)

diferencias_al_cuadrado = (arreglo - media) ** 2

varianza = np.sum(diferencias_al_cuadrado) / len(arreglo)

print("Varianza:", varianza)


Varianza: 2.0


In [8]:
import numpy as np

arreglo_aleatorio = np.random.randn(10)

print(arreglo_aleatorio)

[ 1.29682289 -1.34953798 -0.54736846 -1.715922    0.0314111  -0.19102622
  1.21276903 -0.26324973 -0.81301543  1.82204586]
